### ISSUE TITLE
OUTOUP OF CRUD

### ISSUE THREAD

**Issue by Odile-nza** [nzambazamariya/hazaTask#2]
#
![postPatient](https://user-images.githubusercontent.com/41570723/106971078-d860c100-6756-11eb-946a-d4f5e4216d2e.PNG)
Create API

**Comment by Odile-nza** [comment]
#GET Api
![getallPatient](https://user-images.githubusercontent.com/41570723/106971162-02b27e80-6757-11eb-9256-a8df7651814f.PNG)

**Comment by Odile-nza** [comment]
#Get single data Api
![getPatient](https://user-images.githubusercontent.com/41570723/106971271-3e4d4880-6757-11eb-9466-6d6164c6992a.PNG)

**Comment by Odile-nza** [comment]
#
![updatepatient](https://user-images.githubusercontent.com/41570723/106971319-5cb34400-6757-11eb-87b4-3e0f46e39db4.PNG)
Update Api

**Comment by nzambazamariya** [comment]
#delete Api
![Uploading deletepatient.PNG…]()

**Comment by nzambazamariya** [comment]
#DELETE API
![Uploading deletepatient.PNG…]()

**Comment by Odile-nza** [comment]
#DELETE API
![DELETEAPI](https://user-images.githubusercontent.com/41570723/106972110-e3b4ec00-6758-11eb-99d5-a69c58574e4d.PNG)
